- name: restart node 2 dan node 3
  hosts: node-elk
  become: true

  tasks:
  - name: increase timeout
    shell: sed -i.old 's/TimeoutStartSec=75/TimeoutStartSec=9999/'  /usr/lib/systemd/system/elasticsearch.service
  - name: reload daemon
    shell: sudo systemctl daemon-reload
  - name: enable elastic
    shell: sudo systemctl enable elasticsearch.service
  - name: start elastic
    shell: sudo systemctl start elasticsearch.service
  - name: restart elastic
    shell: sudo systemctl restart elasticsearch.service
  - name: status elastic
    shell: sudo systemctl status elasticsearch.service
    register: results
  - name: show status elastic
    debug:
        msg: "{{ results.stdout_lines }}"
  - name: show port
    shell: ss -altnp | grep -iE '92|93'
    register: results
  - name: show port
    debug:
        msg: "{{ results.stdout_lines }}"
 